"""Sounds generated by pyfxr for use in the game."""
import pyfxr
import pygame.mixer

hit = pygame.mixer.Sound(buffer=pyfxr.SFX(
    base_freq=0.369,
    freq_ramp=-0.643,
    duty=0.569,
    env_attack=0.0,
    env_sustain=0.069,
    env_decay=0.184,
    wave_type=pyfxr.WaveType.SQUARE,
))

jump1 = pygame.mixer.Sound(buffer=pyfxr.SFX(
    base_freq=0.23,
    freq_ramp=0.225,
    duty=0.55,
    env_attack=0.0,
    env_sustain=0.137,
    env_decay=0.235,
    wave_type=pyfxr.WaveType.SQUARE,
))
jump2 = pygame.mixer.Sound(buffer=pyfxr.SFX(
    base_freq=0.27,
    freq_ramp=0.225,
    duty=0.55,
    env_attack=0.0,
    env_sustain=0.137,
    env_decay=0.235,
    wave_type=pyfxr.WaveType.SQUARE,
))

collect = pygame.mixer.Sound(buffer=pyfxr.SFX(
    base_freq=0.72,
    env_sustain=0.14,
    env_decay=0.38,
    env_punch=0.47,
    wave_type=pyfxr.WaveType.SQUARE,
))
